### ISSUE TITLE
ViruZ Mod compatible

### ISSUE THREAD

**Issue by jus61** [10Dozen/dzn_dynai#32]
Can you tell me if the script is compatible with the ViruZ Mod http://www.viruzmod.com

**Comment by 10Dozen** [comment]
Actually, have no idea what ViruZ mod is. But dynai is a script, so it will work anyway if you add it to your mission.

If ViruZ mod has some ai-behavior features, then it will affect dynai's ai-tweaks for sure.

**Comment by jus61** [comment]
THX will try it
