### ISSUE TITLE
dzn_fnc_dynai_moveZone: zone with indoors units spawns outside

### ISSUE THREAD

**Issue by OneScheer** [10Dozen/dzn_dynai#56]
HQ_Guard spawns indoors  group outside of zone. 

[Der Flug Nach Kunara 1A.zip](https://github.com/10Dozen/dzn_dynai/files/3968093/Der.Flug.Nach.Kunara.1A.zip)

**Comment by 10Dozen** [comment]
Fixed in https://github.com/10Dozen/dzn_dynai/pull/57
